### ISSUE TITLE
Output RAML

### ISSUE THREAD

**Issue by abreksa4** [thebinarypenguin/raml-cop#4]
Is it possible to output RAML as well as JSON, in order to generate a single RAML file with external files, such as schema and examples?

**Comment by thebinarypenguin** [comment]
No.

RAML Cop is a simple CLI wrapper around  [raml-org/raml-js-parser](https://github.com/raml-org/raml-js-parser). It is designed to be used as a "linter" and nothing more. The only reason the "output JSON" option exists is because the underlying parser has that option and I figured I'd expose it via RAML Cop as well (even if it doesn't seem very useful)

**Comment by abreksa4** [comment]
Good to know, I figured that was case.

Thanks

-Andrew Breksa
